FROM node
WORKDIR /app/
COPY ["package.json", "package-lock.json", "./"]
RUN ["npm", "install"]
RUN ["npm", "install","serve","-g"]
COPY ["src/", "./src/"]
COPY ["public/","./public/"]
RUN ["npm", "run", "build"]
CMD ["serve","-s", "build"]