FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["nvul_server.csproj", "nvul_server/"]
RUN dotnet restore "nvul_server/nvul_server.csproj"
COPY . ./nvul_server
WORKDIR "/src/nvul_server"
RUN dotnet build "nvul_server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "nvul_server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "nvul_server.dll"]